apiVersion: v1
kind: Namespace
metadata:
  name: NAMESPACE

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAMESPACE-deployment-crashjet
  namespace: NAMESPACE
  labels:
    app: app
spec:
  #replicas: MIN_REPLICAS
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      nodeSelector:
        app: x86_64
      tolerations:
      - effect: NoSchedule
        key: dedicatedTo
        operator: Equal
        value: x86_64
      containers:
      - name: fiber
        image: CONTAINER_IMAGE
        envFrom:
        - configMapRef:
            name: app-configs
            optional: true
        - secretRef:
            name: app-secrets
            optional: true
        env:
        - name: GAME_ID
          value: SGJET101
        - name: TABLE_ID
          value: STGJET101  
        # ports:
        # - containerPort: 8080
        resources:
            requests:
              memory: "MIN_MEMORY"
              cpu: "MIN_CPU"
            limits:
              memory: "MAX_MEMORY"
              cpu: "MAX_CPU"


